config/routes.rb
Rails.application.routes.draw do
  resources :ships, :worlds, :planets, :items, :player_ships, :captains, :users, :planet_inventories

  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out

  root 'home#index'
end

app/models/captain.rb
class Captain < ActiveRecord::Base
  belongs_to :user

  belongs_to :world
  #has_one :cartel
  has_one :ship
end

app/models/cartel.rb
class Cartel < ActiveRecord::Base
	has_many :captains
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :planet_inventory
end

app/models/planet.rb
class Planet < ActiveRecord::Base
	belongs_to :world
	belongs_to :captain

	has_many :planet_inventories
end

app/models/planet_inventory.rb
class PlanetInventory < ActiveRecord::Base
  belongs_to :planet
  belongs_to :item

  def item_price(a, b) #a = item_id, b = price_modifier
   	i = Item.find(a)
  	return i.base_price * b
  end
end

app/models/player_ship.rb
class PlayerShip < ActiveRecord::Base
  belongs_to :captain
  belongs_to :ship
end

app/models/ship.rb
class Ship < ActiveRecord::Base
	has_many :player_ships
end

app/models/ship_inventory.rb
class ShipInventory < ActiveRecord::Base
  belongs_to :ship
  belongs_to :item
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :password
	
	#relationships
	has_many :captains

	#validations
	validates :username, presence: true, if: :username
	validates :email, presence: true,
										uniqueness: true,
										if: :email

	validates_presence_of :password, if: :password, :on => :create
	validates_confirmation_of :password

	#before actions
	before_save :encrypt_password, :unless => Proc.new { |u| u.password.blank? }
	before_save { self.email = email.downcase }

	def to_s
		self.username
	end

	def encrypt_password
		self.password_salt = BCrypt::Engine.generate_salt
		self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
	end

  def self.authenticate(email, password)
  	#need to change this over to username - Maybe either/or?
	  user = User.where(:email => email).first
	  if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
	  	user
	  else
	  	nil
	  end
  end

end

app/models/world.rb
class World < ActiveRecord::Base
	has_many :captains
	has_many :planets
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :set_item, only: [:edit, :update, :destroy]

  def index
  	@items = Item.all
  end

  def new
  	@item = Item.new
  end

  def edit
  end

  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to new_item_path, notice: 'item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :base_price)
   end
end

app/controllers/ships_controller.rb
class ShipsController < ApplicationController
  before_action :set_ship, only: [:show, :edit, :update, :destroy]

  def index
  	@ships = Ship.all
  end

  def show
  end

  def new
    @ship = Ship.new
  end

  def edit
  end

  def create
    @ship = Ship.new(ship_params)

    respond_to do |format|
      if @ship.save
        format.html { redirect_to @ship, notice: 'Ship was successfully created.' }
        format.json { render :show, status: :created, location: @ship }
      else
        format.html { render :new }
        format.json { render json: @ship.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @ship.update(ship_params)
        format.html { redirect_to @ship, notice: 'Ship was successfully updated.' }
        format.json { render :show, status: :ok, location: @ship }
      else
        format.html { render :edit }
        format.json { render json: @ship.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @ship.destroy
    respond_to do |format|
      format.html { redirect_to ships_url, notice: 'Ship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ship
      @ship = Ship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ship_params
      params.require(:ship).permit(:name, :base_fuel, :reactor_upgrades, :torpedo_bays, :base_cargo, :max_cargo, :ship_fighting_odds, :max_fighters, :max_shields, :cost)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update]

	def create
		@user = User.new(user_params)
		
		if @user.save
			flash[:notice] = "Account Created Successfully!"
			session[:user_id] = @user.id
			redirect_to root_path
		else
			flash[:alert] = "There was a problem creating your account. Please try again."
			redirect_to :back
		end
	end

	def index
		@users = User.all
	end

	def edit
	end

	def show
	end

	# PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
   	new_params = user_params.delete_blanks!

  	respond_to do |format|
    if @user.update_attributes(new_params)
    	format.html { redirect_to edit_user_path(@user.id), notice: 'User was successfully updated.' }
      format.json { render :show, status: :ok, location: @user }
    else
      format.html { render :edit }
      format.json { render json: @user.errors, status: :unprocessable_entity }
    end
  end
end

private
	def set_user
    @user = User.find(params[:id])
  end

	def user_params
		params.require(:user).permit(:email, :username, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/captains_helper.rb
module CaptainsHelper
end

app/helpers/cartel_helper.rb
module CartelHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/planet_helper.rb
module PlanetHelper
end

app/helpers/player_ships_helper.rb
module PlayerShipsHelper
end

app/helpers/ship_helper.rb
module ShipHelper
end

app/helpers/world_helper.rb
module WorldHelper
end

app/views/items/_form.html.haml
= simple_form_for @item do |f|
	= f.error_notification
	
	= f.input :name
	= f.input :base_price

	= f.button :submit

app/views/items/edit.html.haml
.container.well
	.col-md-6
		= render "form"

		= link_to "Back", items_path, :class => "btn btn-default"

app/views/items/index.html.haml
.container.well
	.col-md-6
		%h1 Listing All Items

		%table.table.table-striped
			%tr
				%th Item Name
				%th Base Price
			- @items.each do |item|
				%tr
					%td= link_to item.name, edit_item_path(item.id)
					%td= item.base_price

		= link_to "New Item", new_item_path, :class => "btn btn-default"

app/views/items/new.html.haml
.container.well
	.col-md-6
		.h1 New Item

		= render "form"

app/views/items/show.html.haml
= link_to "Back", items_path, :class => "btn btn-default"

app/views/ships/_form.html.haml
= simple_form_for(@ship) do |f|
  = f.error_notification
  %tr
    %td= f.input :name
  %tr  
    %td= f.input :base_fuel, :label => "Standard Jump Reactor Power"
  %tr
    %td= f.input :reactor_upgrades
  %tr
    %td= f.input :torpedo_bays
  %tr
    %td= f.input :base_cargo, :label => "Base Cargo Spaces Included"
  %tr
    %td= f.input :max_cargo, :label => "Max Cargo Spaces"
  %tr
    %td= f.input :ship_fighting_odds
  %tr
    %td= f.input :max_fighters
  %tr
    %td= f.input :max_shields
  %tr
    %td= f.input :cost
  %tr
    %td= f.button :submit, :class => "btn btn-success"

app/views/ships/edit.html.haml
.container.well
	.col-md-6
		=render "form"

app/views/ships/index.html.haml
.container.well
	.col-md-6
		%table.table.table-striped
			- @ships.each do |ship|
				%tr
					%td= ship.name
					%td= link_to "View", ship, :class => "btn btn-sm btn-default"
					%td= link_to "Edit", edit_ship_path(ship), :class => "btn btn-sm btn-default"
		= link_to "New Ship", new_ship_path, :class => "btn btn-default"

app/views/ships/new.html.haml
.container.well
  .col-md-6
    %table.table
      = render "form"

app/views/ships/show.html.haml
.container.well
  .col-md-6
    %table.table.table-striped
      %tr 
        %td Name
        %td= @ship.name
      %tr
        %td Base Reactor
        %td= @ship.base_fuel
      %tr
        %td Reactor Upgrades Available
        %td= @ship.reactor_upgrades
      %tr
        %td Torpedo Bays
        %td= @ship.torpedo_bays
      %tr
        %td Base Cargo
        %td= @ship.base_cargo
      %tr
        %td Max Cargo
        %td= @ship.max_cargo
      %tr
        %td Ship Fighting Odds
        %td= @ship.ship_fighting_odds
      %tr
        %td Max Fighters
        %td= @ship.max_fighters
      %tr
        %td Max Shields
        %td= @ship.max_shields
    = link_to "Back", ships_path, :class => "btn btn-default"
    = link_to "New Ship", new_ship_path, :class => "btn btn-default"