config/routes.rb
Rails.application.routes.draw do
  resources :ships, :worlds, :planets, :items, :player_ships, :captains, :users, :planet_inventories

  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out

  root 'home#index'
end

app/models/captain.rb
class Captain < ActiveRecord::Base
  belongs_to :user

  belongs_to :world
  #has_one :cartel
  has_one :ship
end

app/models/cartel.rb
class Cartel < ActiveRecord::Base
	has_many :captains
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :planet_inventory
end

app/models/planet.rb
class Planet < ActiveRecord::Base
	belongs_to :world
	belongs_to :captain

	has_many :planet_inventories
end

app/models/planet_inventory.rb
class PlanetInventory < ActiveRecord::Base
  belongs_to :planet
  belongs_to :item

  def item_price(a, b) #a = item_id, b = price_modifier
   	i = Item.find(a)
  	return i.base_price * b
  end
end

app/models/player_ship.rb
class PlayerShip < ActiveRecord::Base
  belongs_to :captain
  belongs_to :ship
end

app/models/ship.rb
class Ship < ActiveRecord::Base
	has_many :player_ships
end

app/models/ship_inventory.rb
class ShipInventory < ActiveRecord::Base
  belongs_to :ship
  belongs_to :item
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :password
	
	#relationships
	has_many :captains

	#validations
	validates :username, presence: true, if: :username
	validates :email, presence: true,
										uniqueness: true,
										if: :email

	validates_presence_of :password, if: :password, :on => :create
	validates_confirmation_of :password

	#before actions
	before_save :encrypt_password, :unless => Proc.new { |u| u.password.blank? }
	before_save { self.email = email.downcase }

	def to_s
		self.username
	end

	def encrypt_password
		self.password_salt = BCrypt::Engine.generate_salt
		self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
	end

  def self.authenticate(email, password)
  	#need to change this over to username - Maybe either/or?
	  user = User.where(:email => email).first
	  if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
	  	user
	  else
	  	nil
	  end
  end

end

app/models/world.rb
class World < ActiveRecord::Base
	has_many :captains
	has_many :planets
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :set_item, only: [:edit, :update, :destroy]

  def index
  	@items = Item.all
  end

  def new
  	@item = Item.new
  end

  def edit
  end

  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to new_item_path, notice: 'item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :base_price)
   end
end

app/controllers/player_ships_controller.rb
class PlayerShipsController < ApplicationController
  before_action :set_player_ship, only: [:show, :edit, :update, :destroy]

  # GET /player_ships
  # GET /player_ships.json
  def index
    @player_ships = PlayerShip.all
  end

  # GET /player_ships/1
  # GET /player_ships/1.json
  def show
  end

  # GET /player_ships/new
  def new
    @player_ship = PlayerShip.new
  end

  # GET /player_ships/1/edit
  def edit
  end

  # POST /player_ships
  # POST /player_ships.json
  def create
    @player_ship = PlayerShip.new(player_ship_params)

    respond_to do |format|
      if @player_ship.save
        format.html { redirect_to @player_ship, notice: 'Player ship was successfully created.' }
        format.json { render :show, status: :created, location: @player_ship }
      else
        format.html { render :new }
        format.json { render json: @player_ship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /player_ships/1
  # PATCH/PUT /player_ships/1.json
  def update
    respond_to do |format|
      if @player_ship.update(player_ship_params)
        format.html { redirect_to @player_ship, notice: 'Player ship was successfully updated.' }
        format.json { render :show, status: :ok, location: @player_ship }
      else
        format.html { render :edit }
        format.json { render json: @player_ship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /player_ships/1
  # DELETE /player_ships/1.json
  def destroy
    @player_ship.destroy
    respond_to do |format|
      format.html { redirect_to player_ships_url, notice: 'Player ship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player_ship
      @player_ship = PlayerShip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_ship_params
      params.require(:player_ship).permit(:captain_id, :ship_id, :name, :fuel_total, :fuel_remaining, :cargo_spaces, :fighters)
    end
end

app/controllers/ships_controller.rb
class ShipsController < ApplicationController
  before_action :set_ship, only: [:show, :edit, :update, :destroy]

  def index
  	@ships = Ship.all
  end

  def show
  end

  def new
    @ship = Ship.new
  end

  def edit
  end

  def create
    @ship = Ship.new(ship_params)

    respond_to do |format|
      if @ship.save
        format.html { redirect_to @ship, notice: 'Ship was successfully created.' }
        format.json { render :show, status: :created, location: @ship }
      else
        format.html { render :new }
        format.json { render json: @ship.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @ship.update(ship_params)
        format.html { redirect_to @ship, notice: 'Ship was successfully updated.' }
        format.json { render :show, status: :ok, location: @ship }
      else
        format.html { render :edit }
        format.json { render json: @ship.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @ship.destroy
    respond_to do |format|
      format.html { redirect_to ships_url, notice: 'Ship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ship
      @ship = Ship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ship_params
      params.require(:ship).permit(:name, :base_fuel, :reactor_upgrades, :torpedo_bays, :base_cargo, :max_cargo, :ship_fighting_odds, :max_fighters, :max_shields, :cost)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/captains_helper.rb
module CaptainsHelper
end

app/helpers/cartel_helper.rb
module CartelHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/planet_helper.rb
module PlanetHelper
end

app/helpers/player_ships_helper.rb
module PlayerShipsHelper
end

app/helpers/ship_helper.rb
module ShipHelper
end

app/helpers/world_helper.rb
module WorldHelper
end

app/views/player_ships/_form.html.haml
= simple_form_for(@player_ship) do |f|
  = f.error_notification
  = f.association :captain
  = f.association :ship
  = f.input :name
  = f.input :fuel_total
  = f.input :fuel_remaining
  = f.input :cargo_spaces
  = f.input :fighters

  = f.button :submit

app/views/player_ships/edit.html.haml
.container.well
	.col-md-6
		%h1 Editing Player Ship
		= render 'form'

		%br/
		= link_to 'Show', @player_ship, :class => "btn btn-default"
		= link_to 'Back', player_ships_path, :class => "btn btn-default"

app/views/player_ships/index.html.haml
.container.well
  .col-md-6
    %h3 Listing Player Ships
    %table.table.table-striped  
      %tr
        %th Captain
        %th Ship Type
        %th Ship Name
        %th Fuel Total
        %th Fuel Remaining
        %th Cargo Spaces
        %th Fighters
        %th{:colspan => "3"}

      - @player_ships.each do |player_ship|
        %tr
          %td= player_ship.captain.name
          %td= player_ship.ship.name
          %td= player_ship.name
          %td= player_ship.fuel_total
          %td= player_ship.fuel_remaining
          %td= player_ship.cargo_spaces
          %td= player_ship.fighters
          %td= link_to 'Show', player_ship, :class => "btn btn-sm btn-default"
          %td= link_to 'Edit', edit_player_ship_path(player_ship), :class => "btn btn-sm btn-default"
          %td= link_to 'Destroy', player_ship, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-sm btn-danger"
    
    %br/
    = link_to 'New Player Ship', new_player_ship_path, :class => "btn btn-default"

app/views/player_ships/new.html.haml
.container.well
	.col-md-6
		%h1 New Player Ship
		= render 'form'

		%br/
		= link_to 'Back', player_ships_path, :class => "btn btn-default"

app/views/player_ships/show.html.haml
.container.well
  .col-md-6
    %table.table.table-striped
      %tr
        %td Captain:
        %td= @player_ship.captain.name
      %tr
        %td Ship Type:
        %td= @player_ship.ship.name
      %tr
        %td Ship Name:
        %td= @player_ship.name
      %tr
        %td Fuel total:
        %td= @player_ship.fuel_total
      %tr
        %td Fuel remaining:
        %td= @player_ship.fuel_remaining
      %tr
        %td Cargo spaces:
        %td= @player_ship.cargo_spaces
      %tr
        %td Fighters:
        %td= @player_ship.fighters
    
    = link_to 'Edit', edit_player_ship_path(@player_ship), :class => "btn btn-default"
    = link_to 'Back', player_ships_path, :class => "btn btn-default"