config/routes.rb
Rails.application.routes.draw do
  resources :ships, :worlds, :planets, :items, :player_ships, :captains, :users, :planet_inventories

  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out

  root 'home#index'
end

app/models/captain.rb
class Captain < ActiveRecord::Base
  belongs_to :user

  belongs_to :world
  #has_one :cartel
  has_one :ship
end

app/models/cartel.rb
class Cartel < ActiveRecord::Base
	has_many :captains
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :planet_inventory
end

app/models/planet.rb
class Planet < ActiveRecord::Base
	belongs_to :world
	belongs_to :captain

	has_many :planet_inventories
end

app/models/planet_inventory.rb
class PlanetInventory < ActiveRecord::Base
  belongs_to :planet
  belongs_to :item

  def item_price(a, b) #a = item_id, b = price_modifier
   	i = Item.find(a)
  	return i.base_price * b
  end
end

app/models/player_ship.rb
class PlayerShip < ActiveRecord::Base
  belongs_to :captain
  belongs_to :ship
end

app/models/ship.rb
class Ship < ActiveRecord::Base
	has_many :player_ships
end

app/models/ship_inventory.rb
class ShipInventory < ActiveRecord::Base
  belongs_to :ship
  belongs_to :item
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :password
	
	#relationships
	has_many :captains

	#validations
	validates :username, presence: true, if: :username
	validates :email, presence: true,
										uniqueness: true,
										if: :email

	validates_presence_of :password, if: :password, :on => :create
	validates_confirmation_of :password

	#before actions
	before_save :encrypt_password, :unless => Proc.new { |u| u.password.blank? }
	before_save { self.email = email.downcase }

	def to_s
		self.username
	end

	def encrypt_password
		self.password_salt = BCrypt::Engine.generate_salt
		self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
	end

  def self.authenticate(email, password)
  	#need to change this over to username - Maybe either/or?
	  user = User.where(:email => email).first
	  if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
	  	user
	  else
	  	nil
	  end
  end

end

app/models/world.rb
class World < ActiveRecord::Base
	has_many :captains
	has_many :planets
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/captains_helper.rb
module CaptainsHelper
end

app/helpers/cartel_helper.rb
module CartelHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/planet_helper.rb
module PlanetHelper
end

app/helpers/player_ships_helper.rb
module PlayerShipsHelper
end

app/helpers/ship_helper.rb
module ShipHelper
end

app/helpers/world_helper.rb
module WorldHelper
end

app/views/layouts/application.html.haml
!!!
%html
	%head
		%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
		%title SpaceGame
		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
		= javascript_include_tag 'application', 'data-turbolinks-track' => true
		= csrf_meta_tags
	
	%body
		%nav{ :class => "navbar navbar-inverse" }
			.container-fluid
				.navbar-header
					%button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
						%span.sr-only Toggle navigation
						%span.icon-bar
						%span.icon-bar
						%span.icon-bar
					%a.navbar-brand{ :href => "/" }	Space Game
				#bs-example-navbar-collapse-1.collapse.navbar-collapse
					%ul.nav.navbar-nav
						- if current_user
							- if current_user.admin
								%li.dropdown{:role => "presentation"}
									%a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
										Admin Functions
										%span.caret
									%ul.dropdown-menu{:role => "menu"}
										%li= link_to "Users", users_path
										%li= link_to "Captains", captains_path
										%li= link_to "Worlds", worlds_path
										%li= link_to "Planets", planets_path
										%li= link_to "Ships", ships_path
										%li= link_to "Items", items_path
										%li= link_to "Player Ships", player_ships_path
										%li= link_to "Planet Inventories", planet_inventories_path
					%ul.nav.navbar-nav.navbar-right
						- if user_signed_in?
							%li= link_to "Logged in as #{current_user.username}", edit_user_path(current_user.id)
							%li= link_to "Logout", log_out_path
						- else
							%li= link_to "Sign up", new_user_path
							%li= link_to "Login", log_in_path
		


			- if notice
				%p{ :class => "alert alert-success" }
					= notice
			- if alert
				%p{ :class => "alert alert-danger" }
					= alert

		= yield